"""TypeScript types for one spec, for `/types/<name>.ts` and `apiwarden types`.

Every component schema becomes an exported type, and every operation gets the
types a caller actually writes against: `<Operation>Params` (path and query),
`<Operation>Request` (the JSON body) and `<Operation>Response` (the success
body). A frontend fetches the file in its build, so a schema change reaches the
compiler instead of waiting to surface as a runtime bug.

The output is deterministic — no timestamp or hash, stable order — so a spec
change that touches no schema, parameter or description leaves the file as it
was, and a diff of it shows exactly what moved.
"""

from __future__ import annotations

import json
import re
from typing import Any

from .examples import json_media
from .index import _fallback_id
from .loader import Spec, resolve_deep, resolve_ref

_IDENT = re.compile(r"^[A-Za-z_$][A-Za-z0-9_$]*$")
_SCHEMA_REF = "#/components/schemas/"


def type_name(raw: str) -> str:
    """A PascalCase TypeScript identifier from a schema name or operationId."""
    parts = [p for p in re.split(r"[^A-Za-z0-9]+", raw) if p]
    name = "".join(p[:1].upper() + p[1:] for p in parts) or "Unnamed"
    return "_" + name if name[0].isdigit() else name


def typescript_for(spec: Spec) -> str:
    data = spec.data
    schemas = (data.get("components") or {}).get("schemas") or {}
    names = {raw: type_name(raw) for raw in schemas}
    taken = set(names.values())

    out = [
        # No version or hash here: the file should change only when a type does.
        f"// Generated by apiwarden from the \"{spec.name}\" spec ({spec.title}).",
        "// Do not edit: fetch it again when the API changes.",
        "",
    ]

    for raw, schema in schemas.items():
        out.append(_declare(names[raw], schema, names, data))
        out.append("")

    for url, method, operation, shared in spec.operations():
        base = type_name(operation.get("operationId") or _fallback_id(method, url))
        merged = [*shared, *(operation.get("parameters") or [])]
        for suffix, schema, doc in _operation_types(data, operation, merged):
            name = _unique(base + suffix, taken)
            comment = f"{method.upper()} {url}" + (f" — {doc}" if doc else "")
            out.append(_declare(name, schema, names, data, comment=comment))
            out.append("")

    return "\n".join(out).rstrip("\n") + "\n"


def _unique(name: str, taken: set[str]) -> str:
    while name in taken:
        name += "Type"
    taken.add(name)
    return name


def _operation_types(data: dict[str, Any], operation: dict[str, Any], parameters: list[Any]):
    """(suffix, schema, doc) for each type an operation yields."""
    params = [p for p in resolve_deep(data, parameters) if isinstance(p, dict) and p.get("in") in ("path", "query")]
    if params:
        properties = {p["name"]: _with_description(p.get("schema") or {}, p) for p in params if "name" in p}
        required = [p["name"] for p in params if p.get("required") or p.get("in") == "path"]
        yield "Params", {"type": "object", "properties": properties, "required": required}, "path and query parameters"

    body = operation.get("requestBody")
    if isinstance(body, dict):
        body = _deref(data, body)
        chosen = json_media(body.get("content"))
        if chosen and isinstance(chosen[1], dict) and chosen[1].get("schema") is not None:
            yield "Request", chosen[1]["schema"], "request body"

    responses = {str(k): v for k, v in (operation.get("responses") or {}).items()}
    for code in sorted(c for c in responses if c.isdigit() and c.startswith("2")):
        response = _deref(data, responses[code])
        chosen = json_media(response.get("content") if isinstance(response, dict) else None)
        if chosen and isinstance(chosen[1], dict) and chosen[1].get("schema") is not None:
            yield "Response", chosen[1]["schema"], f"{code} response"
        break  # the lowest documented success is the one a caller expects


def _with_description(schema: dict[str, Any], param: dict[str, Any]) -> dict[str, Any]:
    if param.get("description") and "description" not in schema:
        return {**schema, "description": param["description"]}
    return schema


def _deref(data: dict[str, Any], node: Any) -> Any:
    """Follow a top-level $ref (components/responses, components/requestBodies)."""
    if isinstance(node, dict) and isinstance(node.get("$ref"), str) and not node["$ref"].startswith(_SCHEMA_REF):
        try:
            return resolve_ref(data, node["$ref"])
        except (KeyError, IndexError, ValueError):
            return {}
    return node


# ---------------------------------------------------------------- declarations


def _declare(name: str, schema: Any, names: dict[str, str], data: dict[str, Any], comment: str = "") -> str:
    """`export interface` for a plain object, `export type` for everything else."""
    doc = _doc(schema.get("description") if isinstance(schema, dict) else None, comment, schema, indent="")

    if _is_plain_object(schema) and not (isinstance(schema, dict) and "$ref" in schema):
        return f"{doc}export interface {name} {_object_body(schema, names, data, 0)}"
    return f"{doc}export type {name} = {_type(schema, names, data, 0)};"


def _is_plain_object(schema: Any) -> bool:
    return (
        isinstance(schema, dict)
        and (schema.get("type") == "object" or ("properties" in schema and "type" not in schema))
        and not any(k in schema for k in ("allOf", "oneOf", "anyOf", "enum", "nullable"))
        and not isinstance(schema.get("type"), list)
    )


def _doc(description: Any, comment: str, schema: Any, indent: str) -> str:
    lines = []
    if comment:
        lines.append(comment)
    if isinstance(description, str) and description.strip():
        lines.extend(description.strip().splitlines())
    if isinstance(schema, dict) and schema.get("deprecated"):
        lines.append("@deprecated")
    if not lines:
        return ""
    lines = [line.replace("*/", "*\\/").rstrip() for line in lines]
    if len(lines) == 1:
        return f"{indent}/** {lines[0]} */\n"
    body = "".join(f"{indent} * {line}".rstrip() + "\n" for line in lines)
    return f"{indent}/**\n{body}{indent} */\n"


def _object_body(schema: dict[str, Any], names: dict[str, str], data: dict[str, Any], level: int) -> str:
    pad, inner = "  " * level, "  " * (level + 1)
    required = set(schema.get("required") or [])
    lines = []

    for prop, sub in (schema.get("properties") or {}).items():
        key = prop if _IDENT.match(prop) else json.dumps(prop)
        optional = "" if prop in required else "?"
        lines.append(
            _doc(sub.get("description") if isinstance(sub, dict) else None, "", sub, inner)
            + f"{inner}{key}{optional}: {_type(sub, names, data, level + 1)};"
        )

    extra = schema.get("additionalProperties")
    if extra is True or (isinstance(extra, dict) and not extra):
        lines.append(f"{inner}[key: string]: unknown;")
    elif isinstance(extra, dict):
        lines.append(f"{inner}[key: string]: {_type(extra, names, data, level + 1)};")

    if not lines:
        return "{}"
    return "{\n" + "\n".join(lines) + f"\n{pad}}}"


# ---------------------------------------------------------------- types


def _literal(value: Any) -> str:
    return json.dumps(value, ensure_ascii=False)


def _type(schema: Any, names: dict[str, str], data: dict[str, Any], level: int) -> str:
    if schema is True or schema == {}:
        return "unknown"
    if not isinstance(schema, dict):
        return "unknown"

    ref = schema.get("$ref")
    if isinstance(ref, str):
        if ref.startswith(_SCHEMA_REF):
            raw = ref[len(_SCHEMA_REF) :]
            return names.get(raw, type_name(raw))
        try:  # a $ref to something other than a component schema: use what it points at
            return _type(resolve_ref(data, ref), names, data, level)
        except (KeyError, IndexError, ValueError):
            return "unknown"

    nullable = schema.get("nullable") is True
    kind = schema.get("type")
    if isinstance(kind, list):  # OpenAPI 3.1
        nullable = nullable or "null" in kind
        kinds = [k for k in kind if k != "null"]
        kind = kinds[0] if len(kinds) == 1 else None

    text = _core(schema, kind, names, data, level)
    return f"{text} | null" if nullable and text != "null" else text


def _core(schema: dict[str, Any], kind: Any, names: dict[str, str], data: dict[str, Any], level: int) -> str:
    if "const" in schema:
        return _literal(schema["const"])
    if schema.get("enum"):
        return " | ".join(_literal(v) for v in schema["enum"])

    if schema.get("allOf"):
        parts = [_wrap(_type(s, names, data, level)) for s in schema["allOf"]]
        return " & ".join(parts)
    for key in ("oneOf", "anyOf"):
        if schema.get(key):
            return " | ".join(_type(s, names, data, level) for s in schema[key])

    if kind == "array" or (kind is None and "items" in schema):
        item = _type(schema.get("items") or {}, names, data, level)
        return f"({item})[]" if re.search(r"[|&]", item) else f"{item}[]"
    if kind == "object" or (kind is None and "properties" in schema):
        return _object_body(schema, names, data, level)
    if kind == "string":
        return "Blob" if schema.get("format") == "binary" else "string"
    if kind in ("integer", "number"):
        return "number"
    if kind == "boolean":
        return "boolean"
    if kind == "null":
        return "null"
    return "unknown"


def _wrap(text: str) -> str:
    """Parenthesise a union so it stays one operand of an intersection."""
    return f"({text})" if "|" in text and not text.startswith("{") else text
